create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list usystem_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[0]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[1]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[2]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[3]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[4]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[5]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[6]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[7]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[8]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[9]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[10]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[11]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[12]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[13]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[14]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[15]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[16]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[17]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[18]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[19]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[20]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[21]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[22]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[23]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[24]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[25]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[26]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[27]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[28]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[29]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[30]} {usystem_i/dummy_axis_ip_0/inst/m00_axis_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list usystem_i/dummy_axis_ip_0/inst/m00_axis_aresetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list usystem_i/dummy_axis_ip_0/inst/m00_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list usystem_i/dummy_axis_ip_0/inst/m00_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list usystem_i/dummy_axis_ip_0/inst/m00_axis_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
